---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-yiwwhl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-yiwwhl
  template:
    metadata:
      labels:
        app: nginx-yiwwhl
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-yiwwhl-service
spec:
  selector:
    app: nginx-yiwwhl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-yiwwhl-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: yiwwhl.com
    http:
      paths:
      - path: /setup(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: nginx-yiwwhl-service
            port:
              number: 80
